global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'anomaly_detection'
    static_configs:
      - targets: ['anomaly_detection:8000']  # Assuming your anomaly detection app exposes some metrics
