version: '3.8'

services: 
  opensearch:
    image: opensearchproject/opensearch:latest 
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock: 
        soft: -1
        hard: -1 
    ports:
      - "9200:9200"
    networks:
      - opensearch-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest 
    container_name: dashboards 
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    ports:
      - "5601:5601"
    networks:
      - opensearch-net 
    depends_on:
      - opensearch

networks:
  opensearch-net:
    driver: bridge
