global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'anomaly-detector'
    static_configs:
      - targets: ['anomaly-detector:8000']
