version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  anomaly_detection:
    build: .
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - PROMETHEUS_PUSHGATEWAY_URL=http://pushgateway:9091
      - NODE_EXPORTER_URL=http://node_exporter:9100
    depends_on:
      - prometheus
      - pushgateway
      - grafana
      - node_exporter
