version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  anomaly_detection:
    build: .
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - PROMETHEUS_PUSHGATEWAY_URL=http://pushgateway:9091
      - TRAIN_DURATION=14400  # 4 hours in seconds
