global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    # scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
